### ISSUE TITLE
Feature request: Allow giving a name or adding a comment/description to manually created snapshots

### ISSUE THREAD

**Issue by manuelgrabowski** [MehradN/Rollback#1]
Love this mod already, it's almost exactly what I always hoped the native backup functionality would eventually evolve to.

My main use case might be a bit different from other users, I'm not playing much actual singleplayer – even my solo world is hosted on a multiplayer server. What I am using singleplayer for is creative test worlds, and in those it doesn't really matter much what Minecraft day it is, and I also don't back them up automatically on a periodic basis. But I do often want to save them manually at a specific point in time, for example before testing if a certain contraption will work or completely destroy itself due to some small error.

That's why giving a name or comment to each snapshot I create would be incredibly useful. I'd just do `/rollback create Before first TNT duper assembly` and then be able to see the "Before first TNT duper assembly" string somewhere in the list of snapshots I can restore.

**Comment by MehradN** [comment]
I apologize for taking so long to response.
I can add custom names, it shouldn't be a problem. It will be available on v1.0.0. (The next version)

**Comment by manuelgrabowski** [comment]
No rush at all, thanks for taking a look and excited for the next update! :)

**Comment by MehradN** [comment]
I've changed the plans for 1.0.0
This update is released as 0.8.0
